#!/bin/bash
# Generate docker-compose.yml for 41 lens nodes

NODES=41
OUTPUT="docker-compose-41.yml"

cat > "$OUTPUT" << 'EOF'
# Docker Compose for 41-node Lens Cluster
# Generated by generate-compose.sh

version: '3.8'

services:
  # Anycast proxy (simulates anycast BGP in local dev)
  anycast:
    image: nginx:alpine
    ports:
      - "10.7.1.200:5002:80"
    volumes:
      - ./anycast-nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      lens-network:
        ipv4_address: 172.20.0.2
    restart: unless-stopped

EOF

# Generate all lens nodes
for i in $(seq 0 $((NODES - 1))); do
    cat >> "$OUTPUT" << EOF
  lens-node-${i}:
    build: .
    environment:
      - LENS_NODE_ID=${i}
      - LENS_CLUSTER_ID=lens-cluster-local
      - LENS_CLUSTER_SIZE=${NODES}
      - LENS_ANYCAST_IP=172.20.0.2
      - PORT=5002
      - RUST_LOG=info
    volumes:
      - lens-data-${i}:/data
    networks:
      - lens-network
    restart: unless-stopped
    depends_on:
      - anycast

EOF
done

# Generate volumes section
cat >> "$OUTPUT" << EOF
volumes:
EOF

for i in $(seq 0 $((NODES - 1))); do
    echo "  lens-data-${i}:" >> "$OUTPUT"
done

# Generate networks section
cat >> "$OUTPUT" << 'EOF'

networks:
  lens-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
EOF

# Update nginx config with all nodes
cat > anycast-nginx-41.conf << 'NGINX_EOF'
events {
    worker_connections 1024;
}

http {
    upstream lens_cluster {
        least_conn;
NGINX_EOF

for i in $(seq 0 $((NODES - 1))); do
    echo "        server lens-node-${i}:5002;" >> anycast-nginx-41.conf
done

cat >> anycast-nginx-41.conf << 'NGINX_EOF'
    }

    server {
        listen 80;

        location /api/v1/relay/ws {
            proxy_pass http://lens_cluster;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }

        location / {
            proxy_pass http://lens_cluster;
            proxy_set_header Host $host;
        }
    }
}
NGINX_EOF

echo "✓ Generated $OUTPUT with $NODES nodes"
echo "✓ Generated anycast-nginx-41.conf"
echo ""
echo "To deploy:"
echo "  docker-compose -f $OUTPUT up -d"
echo ""
echo "To scale up/down:"
echo "  docker-compose -f $OUTPUT up -d --scale lens-node-0=3"
echo ""
echo "To view logs:"
echo "  docker-compose -f $OUTPUT logs -f lens-node-0"
