FROM node:22-alpine

# Install system packages that are needed for node-gyp and native modules
RUN apk update && \
    apk add py3-setuptools py3-distutils-extra git python3 && \
    apk add --no-cache --virtual .build-deps g++ make python3-dev libffi-dev openssl-dev && \
    corepack enable

WORKDIR /app
