/**
 * plugins/vuetify.ts
 *
 * Framework documentation: https://vuetifyjs.com`
 */

// Styles
import colors from 'vuetify/util/colors';
import '/@/styles/main.scss';
import '/@/styles/settings.scss';
import { createVuetify } from 'vuetify';
import { mdi } from 'vuetify/iconsets/mdi-svg';
import {
  mdiClipboardMultipleOutline,
  mdiClipboardCheckMultipleOutline,
  mdiPlay,
  mdiShareVariant,
  mdiHeart,
  mdiPlus,
  mdiMenuLeft,
  mdiMenuRight,
  mdiClose,
  mdiSkipPrevious,
  mdiPauseCircle,
  mdiPlayCircle,
  mdiSkipNext,
  mdiDotsVertical,
  mdiVolumeOff,
  mdiVolumeHigh,
  mdiRotateLeft,
  mdiShuffle,
  mdiPlusCircle,
  mdiHelpCircleOutline,
  mdiPencil,
  mdiDelete,
  mdiDownload,
  mdiArrowLeft,
  mdiPause,
  mdiFullscreen,
  mdiMenu,
  mdiChevronUp,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronDown,
  mdiCircle,
  mdiCheck,
  mdiAccountSupervisor,
  mdiAccount,
  mdiStar,
  mdiStarOutline,
  mdiStarHalfFull,
  mdiStarPlusOutline,
  mdiBlockHelper,
  mdiGamepad,
  mdiCursorDefaultOutline,
  mdiTelevision,
  mdiMusic,
  mdiTag,
  mdiFolder,
  mdiEye,
  mdiCursorDefaultClick,
  mdiCloseCircle,
  mdiMagnify,
  mdiMenuDown,
  mdiDragVertical,
  mdiCloudCheck,
  mdiPageFirst,
  mdiPageLast,
  mdiWeatherSunny,
  mdiWeatherNight,
  mdiRefresh,
  mdiBookOpenVariant,
  mdiShieldCrown,
  mdiUpload,
  // Additional icons for various pages
  mdiLabel,
  mdiLabelOff,
  mdiServerNetwork,
  mdiVectorPolyline,
  mdiSpeedometer,
  mdiCheckCircle,
  mdiSync,
  mdiAlertCircle,
  mdiAlphaCCircle,
  mdiRayStartArrow,
  mdiBookMusic,
  mdiBookOpenPageVariant,
  mdiPodcast,
  mdiMicrophone,
  mdiAlbum,
  mdiAccountMusic,
  mdiGestureSwipeHorizontal,
  mdiImage,
  mdiFile,
  mdiMovie,
  mdiBookMultiple,
  mdiBraille,
  mdiLoading,
  mdiAlert,
  mdiServer,
  mdiHexagonMultiple,
  mdiWeb,
  mdiPercent,
  mdiHexagon,
  mdiCircleSmall,
  mdiFormatListBulleted,
  mdiCog,
  mdiAlertCircleOutline,
  mdiHelpCircle,
  // Vuetify internal icons
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiMinusBox,
  mdiRadioboxBlank,
  mdiRadioboxMarked,
  mdiArrowUp,
  mdiArrowDown,
  mdiCached,
  mdiUnfoldMoreHorizontal,
  mdiPaperclip,
  mdiMinus,
  mdiCalendar,
  mdiPlusBox,
  mdiInformation,
  mdiExclamation,
  mdiLink,
  mdiClockOutline,
  mdiContentCopy,
  mdiCloudUpload,
  mdiCheckDecagram,
} from '@mdi/js';

const iconsAliasesMapping = {
  'clipboard-multiple-outline': mdiClipboardMultipleOutline,
  'clipboard-check-multiple-outline': mdiClipboardCheckMultipleOutline,
  'play': mdiPlay,
  'share-variant': mdiShareVariant,
  'heart': mdiHeart,
  'plus': mdiPlus,
  'menu-left': mdiMenuLeft,
  'menu-right': mdiMenuRight,
  'close': mdiClose,
  'skip-previous': mdiSkipPrevious,
  'pause-circle': mdiPauseCircle,
  'play-circle': mdiPlayCircle,
  'skip-next': mdiSkipNext,
  'dots-vertical': mdiDotsVertical,
  'volume-off': mdiVolumeOff,
  'volume-high': mdiVolumeHigh,
  'rotate-left': mdiRotateLeft,
  'shuffle': mdiShuffle,
  'plus-circle': mdiPlusCircle,
  'help-circle-outline': mdiHelpCircleOutline,
  'pencil': mdiPencil,
  'delete': mdiDelete,
  'download': mdiDownload,
  'arrow-left': mdiArrowLeft,
  'pause': mdiPause,
  'fullscreen': mdiFullscreen,
  'menu': mdiMenu,
  'chevron-up': mdiChevronUp,
  prev: mdiChevronLeft,
  next: mdiChevronRight,
  'circle': mdiCircle,
  'check': mdiCheck,
  'account-supervisor': mdiAccountSupervisor,
  'account': mdiAccount,
  'star': mdiStar,
  'star-plus-outline': mdiStarPlusOutline,
  'block-helper': mdiBlockHelper,
  'gamepad': mdiGamepad,
  'cursor-default-outline': mdiCursorDefaultOutline,
  'television': mdiTelevision,
  'music': mdiMusic,
  'tag': mdiTag,
  'folder': mdiFolder,
  'eye': mdiEye,
  'cursor-default-click': mdiCursorDefaultClick,
  'close-circle': mdiCloseCircle,
  'magnify': mdiMagnify,
  'menu-down': mdiMenuDown,
  'drag-vertical': mdiDragVertical,
  'cloud-check': mdiCloudCheck,
  'page-first': mdiPageFirst,
  'page-last': mdiPageLast,
  'weather-sunny': mdiWeatherSunny,
  'weather-night': mdiWeatherNight,
  'refresh': mdiRefresh,
  'book-open-variant': mdiBookOpenVariant,
  'shield-crown': mdiShieldCrown,
  'upload': mdiUpload,
  'chevron-left': mdiChevronLeft,
  'chevron-right': mdiChevronRight,
  // Additional icons for various pages
  'label': mdiLabel,
  'label-off': mdiLabelOff,
  'server-network': mdiServerNetwork,
  'vector-polyline': mdiVectorPolyline,
  'speedometer': mdiSpeedometer,
  'check-circle': mdiCheckCircle,
  'check-decagram': mdiCheckDecagram,
  'sync': mdiSync,
  'alert-circle': mdiAlertCircle,
  'alpha-c-circle': mdiAlphaCCircle,
  'ray-start-arrow': mdiRayStartArrow,
  'book-music': mdiBookMusic,
  'book-open-page-variant': mdiBookOpenPageVariant,
  'podcast': mdiPodcast,
  'microphone': mdiMicrophone,
  'album': mdiAlbum,
  'account-music': mdiAccountMusic,
  'gesture-swipe-horizontal': mdiGestureSwipeHorizontal,
  'image': mdiImage,
  'file': mdiFile,
  'movie': mdiMovie,
  'book-multiple': mdiBookMultiple,
  'braille': mdiBraille,
  'loading': mdiLoading,
  'alert': mdiAlert,
  'server': mdiServer,
  'hexagon-multiple': mdiHexagonMultiple,
  'web': mdiWeb,
  'percent': mdiPercent,
  'hexagon': mdiHexagon,
  'circle-small': mdiCircleSmall,
  'format-list-bulleted': mdiFormatListBulleted,
  'cog': mdiCog,
  'alert-circle-outline': mdiAlertCircleOutline,
  'help-circle': mdiHelpCircle,
  'arrow-left': mdiArrowLeft,
  'chevron-down': mdiChevronDown,
  'star-outline': mdiStarOutline,
  'star-half-full': mdiStarHalfFull,
  'arrow-up': mdiArrowUp,
  'arrow-down': mdiArrowDown,
  'cached': mdiCached,
  'unfold-more-horizontal': mdiUnfoldMoreHorizontal,
  'paperclip': mdiPaperclip,
  'minus': mdiMinus,
  'calendar': mdiCalendar,
  'plus-box': mdiPlusBox,
  'information': mdiInformation,
  'exclamation': mdiExclamation,
  'link': mdiLink,
  'clock-outline': mdiClockOutline,
  'contentCopy': mdiContentCopy,
  'cloud-upload': mdiCloudUpload,

  // Vuetify internal component default aliases
  complete: mdiCheck,
  cancel: mdiCloseCircle,
  clear: mdiCloseCircle,
  success: mdiCheckCircle,
  info: mdiInformation,
  warning: mdiExclamation,
  error: mdiAlert,
  dropdown: mdiMenuDown,
  expand: mdiChevronDown,
  collapse: mdiChevronUp,
  first: mdiPageFirst,
  last: mdiPageLast,
  checkboxOn: mdiCheckboxMarked,
  checkboxOff: mdiCheckboxBlankOutline,
  checkboxIndeterminate: mdiMinusBox,
  radioOn: mdiRadioboxMarked,
  radioOff: mdiRadioboxBlank,
  edit: mdiPencil,
  ratingEmpty: mdiStarOutline,
  ratingFull: mdiStar,
  ratingHalf: mdiStarHalfFull,
  loading: mdiLoading,
  delimiter: mdiCircle,
  sort: mdiArrowUp,
  sortAsc: mdiArrowUp,
  sortDesc: mdiArrowDown,
  subgroup: mdiMenuDown,
  file: mdiPaperclip,
  plus: mdiPlus,
  minus: mdiMinus,
  calendar: mdiCalendar,
  treeviewCollapse: mdiMenuDown,
  treeviewExpand: mdiMenuRight,
  menu: mdiMenu,
  close: mdiClose,
};

const vuetify = createVuetify({
  icons: {
    defaultSet: 'mdi',
    aliases: iconsAliasesMapping,
    sets: {
      mdi,
    },
  },
  defaults: {
    global: {
      elevation: 0,
    },
    VTextField: {
      variant: 'solo-filled',
    },
    VFileInput: {
      variant: 'solo-filled',
    },
    VSelect: {
      variant: 'solo-filled',
    },
    VAutocomplete: {
      variant: 'solo-filled',
    },
  },
  theme: {
    defaultTheme: 'dark',
    themes: {
      dark: {
        colors: {
          primary: colors.purple.base,
          'primary-lighten-1': colors.purple.lighten1,
          'primary-darken-1': colors.purple.darken1,
          'primary-accent': colors.purple.accent2,
          background: '#000000',
          surface: '#000000',
          'surface-variant': '#0a0a0a',
          // Network visualization colors
          'server-node': colors.purple.base,
          'browser-node': '#546e7a',  // Light grey-blue for dark mode
        },
      },
      light: {
        colors: {
          primary: colors.purple.base,
          'primary-lighten-1': colors.purple.lighten1,
          'primary-darken-1': colors.purple.darken1,
          'primary-accent': colors.purple.accent2,
          background: '#ffffff',
          surface: '#ffffff',
          'surface-variant': '#f5f5f5',
          // Network visualization colors
          'server-node': colors.purple.base,
          'browser-node': '#80deea',  // Light cyan for light mode
        },
      },
    },
  },
});

export default vuetify;
