name: Merge pull request
on: workflow_call

concurrency:
  group: merge-pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Merge pull request
        run: |
          gh pr merge dev