name: Pull request to main
on:
  push:
    branches:
      - dev

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull_request_to_main:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Create pull request if necessary
        run: |
          gh pr create --title "Merge dev" --body "Automatic pull request to merge dev into main" --base main || $? == *already exists*